# === HPA：自动扩缩容（基于 CPU 使用率）===
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: joyk8-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: joyk8-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
